#! /usr/bin/env task
# https://taskfile.dev
version: "3"

# Always run from the project directory (enables running via symlink from anywhere)
dir: "{{.TASKFILE_DIR}}"

dotenv: [".env"]

vars:
  PYTHON: python
  # CLI scripts
  PAT_CLI: "{{.PYTHON}} {{.TASKFILE_DIR}}/pat.py"
  EXTVOLUME_CLI: "{{.PYTHON}} {{.TASKFILE_DIR}}/extvolume.py"
  # Default bucket name for demos
  BUCKET: iceberg-demo
  # AWS region
  AWS_REGION: '{{.AWS_REGION | default "us-west-2"}}'

env:
  # Pass through important env vars
  AWS_REGION: "{{.AWS_REGION}}"
  SNOWFLAKE_DEFAULT_CONNECTION_NAME: "{{.SNOWFLAKE_DEFAULT_CONNECTION_NAME}}"
  SNOWFLAKE_ROLE: "{{.SNOWFLAKE_ROLE}}"
  SNOWFLAKE_DATABASE: "{{.SNOWFLAKE_DATABASE}}"

tasks:
  # ===========================================================================
  # Setup Tasks
  # ===========================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  setup:
    desc: Setup development environment with uv
    cmds:
      - uv venv
      - uv sync
    sources:
      - pyproject.toml
      - requirements.txt
    generates:
      - .venv/**/*

  install:
    desc: Install dependencies
    cmds:
      - uv sync

  # ===========================================================================
  # PAT Management Tasks
  # ===========================================================================

  pat:create:
    desc: Create/rotate PAT for service user
    summary: |
      Creates or rotates a Programmatic Access Token (PAT) for the service user.

      Environment variables (can be set in .env):
        SA_USER: Service account username
        SA_ROLE: Role restriction for the PAT (the role the SA will use)
        SA_ADMIN_ROLE: Admin role for creating policies (default: same as SA_ROLE)
        PAT_OBJECTS_DB: Database for PAT objects
        DOT_ENV_FILE: Path to .env file to update (default: .env in current directory)

      Example:
        task pat:create SA_USER=my_service_user SA_ROLE=demo_role SA_ADMIN_ROLE=sysadmin PAT_OBJECTS_DB=my_db
        task pat:create DOT_ENV_FILE=/path/to/project/.env  # update .env in specific location
        task pat:create  # uses env vars from .env
    cmds:
      - "{{.PAT_CLI}} create {{.CLI_ARGS}}"
    env:
      SA_USER: "{{.SA_USER}}"
      SA_ROLE: "{{.SA_ROLE}}"
      SA_ADMIN_ROLE: "{{.SA_ADMIN_ROLE}}"
      PAT_OBJECTS_DB: "{{.PAT_OBJECTS_DB}}"
      DOT_ENV_FILE: "{{.DOT_ENV_FILE}}"
    vars:
      SA_USER: '{{.SA_USER | default ""}}'
      SA_ROLE: '{{.SA_ROLE | default ""}}'
      SA_ADMIN_ROLE: '{{.SA_ADMIN_ROLE | default ""}}'
      PAT_OBJECTS_DB: '{{.PAT_OBJECTS_DB | default ""}}'
      DOT_ENV_FILE: '{{.DOT_ENV_FILE | default ""}}'

  pat:no-rotate:
    desc: Create PAT without rotating existing
    cmds:
      - "{{.PAT_CLI}} create --no-rotate {{.CLI_ARGS}}"
    env:
      SA_USER: "{{.SA_USER}}"
      SA_ROLE: "{{.SA_ROLE}}"
      SA_ADMIN_ROLE: "{{.SA_ADMIN_ROLE}}"
      PAT_OBJECTS_DB: "{{.PAT_OBJECTS_DB}}"
      DOT_ENV_FILE: "{{.DOT_ENV_FILE}}"
    vars:
      SA_USER: '{{.SA_USER | default ""}}'
      SA_ROLE: '{{.SA_ROLE | default ""}}'
      SA_ADMIN_ROLE: '{{.SA_ADMIN_ROLE | default ""}}'
      PAT_OBJECTS_DB: '{{.PAT_OBJECTS_DB | default ""}}'
      DOT_ENV_FILE: '{{.DOT_ENV_FILE | default ""}}'

  pat:remove:
    desc: Remove PAT and associated objects
    summary: |
      Removes a PAT and associated objects (network policy, auth policy) for a service user.
      Also clears SNOWFLAKE_PASSWORD from .env file.

      Environment variables (can be set in .env):
        SA_USER: Service account username
        PAT_OBJECTS_DB: Database where PAT objects are stored
        DOT_ENV_FILE: Path to .env file to clear credentials from

      Options:
        --pat-only: Only remove the PAT, keep policies
        --drop-user: Also drop the service user

      Example:
        task pat:remove SA_USER=my_service_user PAT_OBJECTS_DB=my_db
        task pat:remove DOT_ENV_FILE=/path/to/.env  # clear specific .env
        task pat:remove -- --pat-only    # only remove PAT
        task pat:remove -- --drop-user   # also drop the user
    cmds:
      - "{{.PAT_CLI}} remove --yes {{.CLI_ARGS}}"
    env:
      SA_USER: "{{.SA_USER}}"
      PAT_OBJECTS_DB: "{{.PAT_OBJECTS_DB}}"
      DOT_ENV_FILE: "{{.DOT_ENV_FILE}}"
    vars:
      SA_USER: '{{.SA_USER | default ""}}'
      PAT_OBJECTS_DB: '{{.PAT_OBJECTS_DB | default ""}}'
      DOT_ENV_FILE: '{{.DOT_ENV_FILE | default ""}}'

  # ===========================================================================
  # External Volume Tasks
  # ===========================================================================

  extvolume:create:
    desc: Create S3 bucket, IAM role, and Snowflake external volume
    summary: |
      Creates all resources needed for a Snowflake external volume:
        - S3 bucket with versioning
        - IAM policy and role
        - Snowflake external volume
        - Updates IAM trust policy with Snowflake's IAM user

      Resources are prefixed with your username by default.

      Environment variables (can be set in .env):
        BUCKET: S3 bucket base name
        EXTERNAL_VOLUME_NAME: Snowflake external volume name

      Example:
        task extvolume:create BUCKET=my-data
        task extvolume:create BUCKET=my-data -- --no-prefix
    cmds:
      - "{{.EXTVOLUME_CLI}} --region {{.AWS_REGION}} create {{.CLI_ARGS}}"
    env:
      BUCKET: "{{.BUCKET}}"
      EXTERNAL_VOLUME_NAME: "{{.EXTERNAL_VOLUME_NAME}}"
    vars:
      BUCKET: '{{.BUCKET | default ""}}'
      EXTERNAL_VOLUME_NAME: '{{.EXTERNAL_VOLUME_NAME | default ""}}'

  extvolume:delete:
    desc: Delete external volume and AWS resources
    summary: |
      Deletes all resources associated with an external volume:
        - Snowflake external volume
        - IAM role and policy
        - Optionally S3 bucket (use --delete-bucket)

      Environment variables (can be set in .env):
        BUCKET: S3 bucket base name
        EXTERNAL_VOLUME_NAME: Snowflake external volume name

      Example:
        task extvolume:delete BUCKET=my-data
        task extvolume:delete BUCKET=my-data -- --delete-bucket --force
    cmds:
      - "{{.EXTVOLUME_CLI}} --region {{.AWS_REGION}} delete {{.CLI_ARGS}}"
    env:
      BUCKET: "{{.BUCKET}}"
      EXTERNAL_VOLUME_NAME: "{{.EXTERNAL_VOLUME_NAME}}"
    vars:
      BUCKET: '{{.BUCKET | default ""}}'
      EXTERNAL_VOLUME_NAME: '{{.EXTERNAL_VOLUME_NAME | default ""}}'
    prompt: "This will delete AWS and Snowflake resources. Continue?"

  extvolume:verify:
    desc: Verify external volume connectivity
    summary: |
      Verifies that Snowflake can connect to the external volume's S3 storage.

      Environment variables (can be set in .env):
        EXTERNAL_VOLUME_NAME: Snowflake external volume name

      Example:
        task extvolume:verify VOLUME=MY_EXTERNAL_VOLUME
        task extvolume:verify  # uses EXTERNAL_VOLUME_NAME from env
    cmds:
      - "{{.EXTVOLUME_CLI}} verify"
    env:
      EXTERNAL_VOLUME_NAME: "{{.VOLUME}}"
    vars:
      VOLUME: '{{.VOLUME | default ""}}'

  extvolume:describe:
    desc: Describe external volume properties
    summary: |
      Shows external volume properties including:
        - STORAGE_AWS_IAM_USER_ARN
        - STORAGE_AWS_EXTERNAL_ID

      Environment variables (can be set in .env):
        EXTERNAL_VOLUME_NAME: Snowflake external volume name

      Example:
        task extvolume:describe VOLUME=MY_EXTERNAL_VOLUME
        task extvolume:describe  # uses EXTERNAL_VOLUME_NAME from env
    cmds:
      - "{{.EXTVOLUME_CLI}} describe"
    env:
      EXTERNAL_VOLUME_NAME: "{{.VOLUME}}"
    vars:
      VOLUME: '{{.VOLUME | default ""}}'

  extvolume:update-trust:
    desc: Update IAM trust policy from external volume
    summary: |
      Re-syncs the IAM trust policy with Snowflake's IAM user ARN.
      Use this if you've recreated the external volume or need to fix trust issues.

      Environment variables (can be set in .env):
        BUCKET: S3 bucket base name
        EXTERNAL_VOLUME_NAME: Snowflake external volume name

      Example:
        task extvolume:update-trust BUCKET=my-data
        task extvolume:update-trust ROLE=my-role VOLUME=MY_VOLUME
        task extvolume:update-trust  # uses env vars
    cmds:
      - "{{.EXTVOLUME_CLI}} --region {{.AWS_REGION}} update-trust {{.CLI_ARGS}}"
    env:
      BUCKET: "{{.BUCKET}}"
      EXTERNAL_VOLUME_NAME: "{{.VOLUME}}"
    vars:
      BUCKET: '{{.BUCKET | default ""}}'
      VOLUME: '{{.VOLUME | default ""}}'

  # ===========================================================================
  # External Volume Quick Start
  # ===========================================================================

  extvolume:up:
    desc: Quick start - create bucket and external volume with defaults
    summary: |
      One-command setup for Iceberg external volumes. Creates:
        - S3 bucket: {username}-{bucket}
        - IAM role/policy
        - External volume: {USERNAME}_{BUCKET}_EXTERNAL_VOLUME

      Environment variables (can be set in .env):
        BUCKET: S3 bucket base name (default: iceberg-demo)

      Example:
        task extvolume:up
        task extvolume:up BUCKET=my-data
    cmds:
      - task: extvolume:create
    env:
      BUCKET: '{{.BUCKET | default "iceberg-demo"}}'

  extvolume:down:
    desc: Tear down - delete bucket and external volume
    summary: |
      Removes all resources created by extvolume:up:
        - Snowflake external volume
        - IAM role/policy  
        - S3 bucket (with all contents)

      Environment variables (can be set in .env):
        BUCKET: S3 bucket base name (default: iceberg-demo)

      Example:
        task extvolume:down
        task extvolume:down BUCKET=my-data
    cmds:
      - task: extvolume:delete
    env:
      BUCKET: '{{.BUCKET | default "iceberg-demo"}}'
    vars:
      CLI_ARGS: "--delete-bucket --force"

  # ===========================================================================
  # Snowflake CLI Shortcuts
  # ===========================================================================

  snow:test:
    desc: Test Snowflake connection
    cmds:
      - snow connection test

  snow:sql:
    desc: Run SQL query (use -- to pass query)
    summary: |
      Run a SQL query against Snowflake.

      Example:
        task snow:sql -- "SELECT CURRENT_TIMESTAMP()"
        task snow:sql -- "SHOW EXTERNAL VOLUMES"
    cmds:
      - snow sql --query "{{.CLI_ARGS}}"

  snow:volumes:
    desc: List all external volumes
    cmds:
      - snow sql --query "SHOW EXTERNAL VOLUMES"

  snow:pats:
    desc: List programmatic access tokens (optionally for a specific user)
    cmds:
      - |
        if [ -n "{{.PAT_USER}}" ]; then
          snow sql --query "SHOW USER PATS FOR USER {{.PAT_USER}}" --format=json
        else
          snow sql --query "SHOW USER PATS" --format=json
        fi
    vars:
      PAT_USER: '{{.PAT_USER | default ""}}'

  # ===========================================================================
  # AWS CLI Shortcuts
  # ===========================================================================

  aws:whoami:
    desc: Show current AWS identity
    cmds:
      - aws sts get-caller-identity

  aws:buckets:
    desc: List S3 buckets (filtered by prefix, defaults to username)
    summary: |
      Lists S3 buckets filtered by a prefix.

      By default, filters by your username ($(whoami)).

      Example:
        task aws:buckets                    # filter by username
        task aws:buckets PREFIX=myproject   # filter by custom prefix
    cmds:
      - |
        prefix="${PREFIX:-$(whoami)}"
        aws s3 ls | grep "$prefix" || echo "No buckets with prefix '$prefix' found"
    env:
      PREFIX: "{{.PREFIX}}"
    vars:
      PREFIX: '{{.PREFIX | default ""}}'

  aws:roles:
    desc: List IAM roles (filtered by prefix, defaults to username)
    summary: |
      Lists IAM roles filtered by a prefix.

      By default, filters by your username ($(whoami)).

      Example:
        task aws:roles                    # filter by username
        task aws:roles PREFIX=myproject   # filter by custom prefix
    cmds:
      - |
        prefix="${PREFIX:-$(whoami)}"
        aws iam list-roles --query "Roles[?contains(RoleName, '$prefix')].{Name:RoleName,Arn:Arn}" --output table
    env:
      PREFIX: "{{.PREFIX}}"
    vars:
      PREFIX: '{{.PREFIX | default ""}}'

  # ===========================================================================
  # Help Tasks
  # ===========================================================================

  help:
    desc: Show usage guide and quick start
    summary: |
      Snowflake External Volume & PAT Manager
      ════════════════════════════════════════

      QUICK START:
        task extvolume:up                  Create external volume (defaults)
        task extvolume:down                Tear down everything

      DETAILED HELP:
        task <task-name> --summary         Show detailed help for any task
        task --list-all                    List all available tasks

      NAMING CONVENTION:
        Resources are prefixed with your username by default.
        Use --no-prefix to disable, --prefix NAME for custom prefix.

      EXAMPLES:
        task extvolume:up                           # Quick start
        task extvolume:create BUCKET=data           # Custom bucket
        task extvolume:create --summary             # Show detailed help
    cmds:
      - task --summary help

  help:naming:
    desc: Explain prefix and naming conventions
    summary: |
      Naming Conventions
      ══════════════════

      Resources are PREFIXED with your username to avoid conflicts in shared AWS accounts.

      EXAMPLE with BUCKET=iceberg-demo (user: ksampath):

        AWS Resources (lowercase, hyphens):
          Bucket:         ksampath-iceberg-demo
          IAM Role:       ksampath-iceberg-demo-snowflake-role
          IAM Policy:     ksampath-iceberg-demo-snowflake-policy

        Snowflake Objects (UPPERCASE, underscores):
          External Volume: KSAMPATH_ICEBERG_DEMO_EXTERNAL_VOLUME
          External ID:     KSAMPATH_ICEBERG_DEMO_EXTERNAL_ID

      PREFIX OPTIONS:
        (default)         Your username is used as prefix
        --prefix NAME     Use custom prefix
        --no-prefix       No prefix (bucket name as-is)

      EXAMPLES:
        task extvolume:create BUCKET=data                    # → {user}-data
        task extvolume:create BUCKET=data -- --no-prefix     # → data
        task extvolume:create BUCKET=data -- --prefix proj   # → proj-data
    cmds:
      - task --summary help:naming

  help:extvolume:
    desc: Show extvolume CLI options
    cmds:
      - "{{.EXTVOLUME_CLI}} --help"
      - "{{.EXTVOLUME_CLI}} create --help"

  help:pat:
    desc: Show pat CLI options
    cmds:
      - "{{.PAT_CLI}} --help"
